services:
  mysql:
    image: mysql
    container_name: prodcat_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=prodcat_db
      - MYSQL_ROOT_PASSWORD=123